### ISSUE TITLE
better crafting recipe

### ISSUE THREAD

**Issue by AlleCraft-alterego** [starforcraft/Centrifuge-Tiers#1]
crafting recipe of centrifuge don't make any logical sense with resourceful bees, not even the bedrock and cobblestone generator has nothing to do with the mod

**Comment by starforcraft** [comment]
The Cobblestone generators are for the Creative Centrifuge to craft it and do you have another idea for crafting recipes for the centrifuges?

**Comment by AlleCraft-alterego** [comment]
I was thinking of something like this, on the right the crafting of the "dough" item and in the center and on the left the upgrades of the centrigughe with dough
![2020-11-14_00 42 02](https://user-images.githubusercontent.com/72225590/99131166-b998d580-2612-11eb-815e-f1f6e4933530.png)
![2020-11-14_00 42 25](https://user-images.githubusercontent.com/72225590/99131170-bbfb2f80-2612-11eb-8a6b-99a857f98876.png)
![2020-11-14_00 42 46](https://user-images.githubusercontent.com/72225590/99131171-be5d8980-2612-11eb-97ab-10bbfdd51da0.png)
![2020-11-14_00 42 57](https://user-images.githubusercontent.com/72225590/99131182-c1587a00-2612-11eb-9a0d-d57f4fe29589.png)
![2020-11-14_00 43 06](https://user-images.githubusercontent.com/72225590/99131187-c3223d80-2612-11eb-972f-658ed14a8adb.png)

**Comment by starforcraft** [comment]
Hmm... ok but the at the last one you can't upgrade the creative Centrifuge. I think you wanted to but the Centrifuge Tier 5 there?

**Comment by starforcraft** [comment]
and on the last photo is that oreo? xD

**Comment by AlleCraft-alterego** [comment]
there is 5 tiers... 5 recipe of tier... 
yes, is a oreo, cannot be craftable and you can only find oreo bees

**Comment by starforcraft** [comment]
ok, I will look if its good ;)
