### ISSUE TITLE
crash on startup on Minecraft version 1.16.4

### ISSUE THREAD

**Issue by Realever** [starforcraft/Centrifuge-Tiers#2]
Hi,
i tried to use your mod for the current minecraft version 1.16.4 but it crash on the startup.
I used Resourceful Bees 1.16.4-0.5.6b and ctiers-1.16.3-1.5.1.jar.
Forge version is 1.16.4-35.1.13.
Here is the crash log: [pastebin](https://pastebin.com/SS2x9MCC)

Edit: it seems that your mod is not compatible with the Resourceful Bees 1.16.4-0.5.6b. 
I have download the version Resourceful Bees 1.16.3-0.5.5b and there don´t comes the crash

**Comment by starforcraft** [comment]
I will maybe make a 1.16.4 Version of the mod the problem is that Resourceful bees has also a Centrifuge Upgrade in 1.16.4: The Elite Centrifuge. I don't know if it's worth it.

I'm not so good in English I hope you understood it ;)

**Comment by starforcraft** [comment]
and it Crashes because Resourceful bees rewrote the Centrifuges. My mod takes the script from Resourceful bees so it tries to catch something but it doesn't exist or is edited.

**Comment by Realever** [comment]
oh ok.I can´t say if it worth it.This is my first time where i play with Resourceful bees and your mod.I´m from germany and my english is not so good good too but I understood everything :)

**Comment by starforcraft** [comment]
ah lol du bist ja auch eine Deutsche Kartoffel ;)

**Comment by starforcraft** [comment]
Ich habe nachgeschaut nope es lohnt sich nicht da die Elite Centrifuge fast genauso ist wie meine Centrifugen... :/

**Comment by Realever** [comment]
du bist auch deutscher? 
danke das du nachgeschaut hast :)
Ich schließe dann diesen thread
