### ISSUE TITLE
Error when loading up

### ISSUE THREAD

**Issue by Craftingblubb** [starforcraft/Centrifuge-Tiers#3]
when i load up the mod in a modpack im encountering the error "java.lang.IllegalAccessError: no such constructor: com.YTrollman.CentrifugeTiers.tileentity.CentrifugeControllerTileEntityTier2.<init>()void/newInvokeSpecial" during the load_registries event phase using ctiers-1.16.3-1.5.1.jar and ResourcefulBees1.16.3-1.16.4-0.5.8b.jar
Thank you for helping

**Comment by starforcraft** [comment]
It happens because your Resourceful Bees Version is 1.16.4

**Comment by starforcraft** [comment]
and I will maybe make a 1.16.4 Version because Resourceful Bees has in the Version his own Upgrades for the Centrifuges.

**Comment by Craftingblubb** [comment]
ok thx
