### ISSUE TITLE
Upgraded Centrifuge uses 3 Honeycomb Blocks at a time.

### ISSUE THREAD

**Issue by j4n3k2212** [starforcraft/Centrifuge-Tiers#4]
Hello,

i have 2 Tier 3 Centrifuges rn and about to upgrade to a Tier 5 soon. 
I realized that the Tier 3 Centrifuge uses 3 Honeycomb Blocks at a time, in every slot. So if every slot is filled with a Stack of Blocks, it leaves each slot with 61 Blocks, BUT outouts only the items for one Block, so 36 per slot of the main output on the tier 3 Centrifuge. Since i didnt made any Tier 4 i cant say if its the same for those or not.

I now used a regulator from refined storage to limit it to 1 Honeycomb block per slot, though i let u still know. :)

maybe u can find a fix

**Comment by starforcraft** [comment]
thx for the Report but with Version are you using?, so I can fix it

**Comment by j4n3k2212** [comment]
ctiers-1.16.3-1.5.1.jar

**Comment by starforcraft** [comment]
hmm.. ok thx i will look what I can do ;)

**Comment by j4n3k2212** [comment]
is it fixed ?
:)
