### ISSUE TITLE
CTeirs Produce More Bottles of Honey than Bottles

### ISSUE THREAD

**Issue by desagas** [starforcraft/Centrifuge-Tiers#5]
1.16.5.36.0.43 Forge, ATM6-1.5.3b, ctiers-1.16.5-1.114;

If, say, a Centrifuge RNG says produce honey bottles at X time, and there are enough bottles for one slot, if multiple slots call for bottles to be produced, it will produce them.

In my setup, I am running comb blocks that have a 25% change of producing 9 bottles, and, on the Gold Tier (2x output). Often, the Centrifuge will say that each slot of the 6 need to produce bottles (18 each), usually maxing at 72 at one time, but can be 18 x 6 at rare times. What the Tiered Centrifuge does, is, even though there are only 64 emptybottles, it will produce its requested amount of honey bottles, ie, 72 or 18 x 6, as listed above. Which means, these TCs are duplicating bottles.

Ideally, It would be nice to increase the max stack size of inputs equal to that of max stack size of outputs, to avoid this, but, perhaps a hard code. Currently, the only way to fix this is to off set the tasks, so that each stack, each of the 6 combs, are slightly varied in their starting processing time.

**Comment by desagas** [comment]
Here is a screen shot of proof: Although, maybe not proof, but know that my system is pumping in bottles via ultimate mek cables, so, it is pretty fast, and extracting from three ultimate cables, so, I guess just my word. Hahah.

![2021-03-04_12 09 19](https://user-images.githubusercontent.com/8404632/110016708-95a4f100-7ce2-11eb-842f-ce29eeb8e220.png)

**Comment by starforcraft** [comment]
Hmm... thanks for the Report I will look what I can do :) (sorry for late reply)
