### ISSUE TITLE
Centrifuges not multiplying outputs in All The Mods 6 1.16.5

### ISSUE THREAD

**Issue by sbradstr** [starforcraft/Centrifuge-Tiers#7]
Tested in a creative world that Creative Centrifuge, Diamond Centrifuge, and Basic Centrifuge are all outputting around 256 ores given a stack of 64 uranium honeycomb blocks (50% chance to drop 9 ores)

I'm assuming this is not expected. Read through the tile entity code and the configs from all the mods and there doesn't seem to be anything obvious.

Ctiers version - 1.121
Resoureful Bees Version - ResourcefulBees-1.16.5-0.6.2b

**Comment by starforcraft** [comment]
Download newest Version of Centrifuge Tiers. The Version that ATM 6 currently has is buggy.

**Comment by sbradstr** [comment]
Verified this solved my problem locally. However getting the server owner to update it might be another problem ;)

**Comment by starforcraft** [comment]
Then good luck ;)
