### ISSUE TITLE
creative centrifuge breaks chunk and spams console 

### ISSUE THREAD

**Issue by darkcamo12** [starforcraft/Centrifuge-Tiers#8]
updated server/client to "All The Mods 6 Version 1.5.7" and after doing so i noticed a chunk error (as in couldn't render the chunk https://i.imgur.com/9c0q5Arh.jpg ) and mass spam in console 

How to reproduce this bug:
run all the mod 6 version 1.5.7 and create a new world, spawn in the 35 creative tier centrifuge casings and the creative centrifuge controller create the multi block structure and then go for a fly making sure you are out of view range of the chunk the centrifuge is in, head back and you will find its just an errored chunk 

here is the error i get https://pastebin.com/PiSGzkFg

**Comment by starforcraft** [comment]
You are the guy on Discord :) But thats not my fault its the fault from resourceful bees "com.resourcefulbees.resourcefulbees.tileentity.multiblocks.centrifuge.CentrifugeCasingTileEntity.func_189515_b(CentrifugeCasingTileEntity.java:67) ~[?:1.16.5-0.6.5b]" So I cant fix that. Can you maybe report this to the Github from Resourceful bees? :)

**Comment by starforcraft** [comment]
Or wait.. forget what I said I will fix that :)

**Comment by starforcraft** [comment]
Fixed and Update pushed :)
